### ISSUE TITLE
wichitalks.com/donate

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#23]
We need to implement a way to capture donations on the site.
A possible candidate is dwolla.com

**Comment by kevinfalting** [comment]
There is a google wallet account set up for wichitalks@gmail.com, however since there are no actual bank accounts configured for the wallet account, money cannot be accepted yet.

**Comment by kevinfalting** [comment]
Would a paypal option work?

**Comment by kevinfalting** [comment]
Here it is: https://wichitalks.givingfuel.com/donate

I need to add a donate button to wichitalks.com and also a wichitalks.com/donate that describes how donations will work and then a button there that will take them to this donation portal.

**Comment by kevinfalting** [comment]
I can quickly set this up.
Wichitalks.com/donate

```
<head>
  <meta http-equiv="refresh" content="0; url=https://wichitalks.givingfuel.com/donate" />
</head>
```

via: http://stackoverflow.com/questions/5411538/redirect-from-an-html-page

**Comment by kevinfalting** [comment]
Can I edit the favicon on the givingfuel donation page?

**Comment by kentonh** [comment]
Is this sill open? I'm not sure what needs to be done.

**Comment by kevinfalting** [comment]
Yes it is, I just haven't had time to think through it. I intend to redesign the website, and I'll be including this as a part of the redesign. I would consider this issue on hold.

**Comment by kevinfalting** [comment]
I've decided that this will just point to a patreon page once I have it up.

**Comment by kevinfalting** [comment]
closing for now. Will reopen when relevant.
