### ISSUE TITLE
Jarae's QA

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#48]
This is an email from Jarae.

> Okay, so this is just a quick precursory look through.
> 
> As we discussed, search for more adjectives for "passion", like "drive" or "conviction"
> Alternative blurb under "No Pitches Allowed": "Speakers are here to teach and share ideas, but with no strings attached."
> 
> Try using "engage" in some places. This encourages the audience to feel more involved.
> 
> Instead of the redundant use of "volunteer", try "to be present", "take part in", "share in, play a part/role in"
> 
> There are several typos for the last paragraph under the Speakers spot (above the Apply to Present button). Here's this revised version: "If you have any questions or are unclear about what will be accepted, we encourage you to apply anyway. We will give you feedback to help you fine tune your application." 
> 
> The site looks decent on mobile and other browsers. I'll keep looking through it!
> 
> Hope this helps!

-- Jarae

**Comment by kevinfalting** [comment]
I mainly left this open for Jarae to add to.

**Comment by cjanzen** [comment]
If the points above haven't been done yet, I don't mind doing them on a rolling basis. That's as you like, but clearing up the text would be easy peasy I think.

**Comment by kevinfalting** [comment]
Yeah, I've already done some of it, but if you see anything else that could be changed, feel free to make suggestions.

Over the next few months, I'll be doing a site redesign. The content will transition over, and I'll still be using Jekyll, but there are a few things I want to do to help the site look better, be more intuitive, and easier to update on the backend.

**Comment by cjanzen** [comment]
It might help if you ~~strikethrough~~ the changes in the issue that you have made, and I'll do the same so you'll know in the future when you redesign. Would that work for you?

**Comment by kevinfalting** [comment]
closing because feedback is old.
