### ISSUE TITLE
Alumni contact info

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#56]
right now the contact info is center aligned, I want this to be left-aligned.

**Comment by kevinfalting** [comment]
Each alumni has their own video page that contains their contact info.
For example: http://wichitalks.com/suzanna_mathews

I think it would look better with the icons lined up.

**Comment by cjanzen** [comment]
Awesome, @kevinfalting. Thanks for the clarification.

**Comment by cjanzen** [comment]
@kevinfalting Can you assign this issue to me please? Thanks.
