### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#58]
Create a page to handle this situation.

**Comment by kevinfalting** [comment]
right now it defaults to github's 404 page, which may confuse visitors.

**Comment by kevinfalting** [comment]
This is pretty beginner friendly.

**Comment by cjanzen** [comment]
Do you have anything in particular you want on the custom 404, and if I make it, are you going to update .htaccess and turn it on, if it's not already, since I don't have access?

**Comment by cjanzen** [comment]
Submitted a PR for this. Hope it's what you had in mind.

**Comment by cjanzen** [comment]
Closing as PR has been merged.

**Comment by cjanzen** [comment]
FYI, I can't close issues, so you'll have to close this one if you're happy w/ the fix. :)

**Comment by kevinfalting** [comment]
fixed and closing.
