### ISSUE TITLE
Incorrect speaker name in URL

### ISSUE THREAD

**Issue by cjanzen** [Wichitalks/wichitalks.github.io#59]
Issue: Dustin Thiry's name is spelled incorrectly: http://wichitalks.com/dutin-thiry

Fix: Update the URL.

**Comment by kevinfalting** [comment]
Good find, all you have to do is update the permalink on his post.

**Comment by KatherineMichel** [comment]
Hope you don't mind, just fixed this. GitHub added it to a prior pull request of mine, which I did not expect. Live and learn.

**Comment by KatherineMichel** [comment]
I ended up reverting the second commit and making it a separate pull request.

**Comment by kevinfalting** [comment]
Thank you @KatherineMichel
