### ISSUE TITLE
Speaker section isn't intuitive on mobile

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#6]
On desktop, when you hover a mouse over a speakers picture, an overlay of information pops up. This doesn't happen on mobile, at least not until you click on it, which then sends you to the link that is embedded.

**Comment by kentonh** [comment]
Should the speakers be turned into a blog list or do you want to add them in manually each time?

**Comment by kevinfalting** [comment]
I would like to maintain the current way it is laid out, just with something a little more telling as to what that picture represents.

I'm not sure I fully understand what you mean though.

**Comment by kevinfalting** [comment]
Added media queries to css file.
Solved with PR #42
