### ISSUE TITLE
Remove .DS_Store, .sass-cache and _site from git

### ISSUE THREAD

**Issue by sethetter** [Wichitalks/wichitalks.github.io#66]
Add `.DS_Store`, `.sass-cache`and `_site`  to `.gitignore`. Should be local only :)

Also remove them from the repo.

**Comment by kevinfalting** [comment]
@sethetter, did you complete this? I see the pull request and I'm pretty sure I merged it.

**Comment by sethetter** [comment]
@kevinfalting I think so!
