### ISSUE TITLE
Wichitalks.com/survey

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#69]
I'd like to have a page dedicated to surveying and gathering information from people who attend so that we can better tailor Wichitalks events and content. 

1. How should the survey be driven? Google survey, or other professional surveying products?
2. Should it be embedded in the site or direct offsite?
3. What is the reward or incentive for participating in the survey?
4. What kind of questions should be asked?

**Comment by kevinfalting** [comment]
Added the page to the site without any navigation to it.

See the webpage at [wichitalks.com/survey](http://wichitalks.com/survey)

The service I'm using is [surveyplanet.com.](https://surveyplanet.com)

Now I need some questions...

**Comment by benblankley** [comment]
What topic should we search speakers out for?
What topic that we have coveres should we not cover again?
If you know a friend whom you invited to this, but they couldn't come, what was their reason for not coming?
What are some simple things we could do to increase the diversity of perspectives in our audience and speakers?

**Comment by mcgraw** [comment]
1. [SurveyMonkey](https://www.surveymonkey.com/), [Typeform](https://www.typeform.com/), [Google Forms](https://www.google.com/forms/about/) are all good.

2. Either. People are not going to care.

3. Providing nothing is going to get a lot of sad faces. Amazon gift cards motivate me. Either it's the chance to win one or a direct payout. 

4. 
> What speaker impacted you the most? Or, put another way, What talk moved you? In what ways?
> What was the least valuable talk you've seen?
> Have you met anyone at a talk who you've kept in touch with?
> What are the top 3 topics you're most curious about?
> ... I'll jam out more later. Gotta run.

**Comment by benblankley** [comment]
I love grocery store and gas station gift cards as giveaways. Everyone needs groceries and fuel.

**Comment by kevinfalting** [comment]
Also, the contact link in the navbar isn't pointing to the correct link. It's trying to access an id on the page that doesn't exist.

**Comment by kevinfalting** [comment]
`/survey` won't be a link in the navbar, but rather we'll link to the page by sharing it. We may even have a link to it in the contact section.

**Comment by kevinfalting** [comment]
It's all working well!
