### ISSUE TITLE
Minor spelling error on the homepage

### ISSUE THREAD

**Issue by southekal** [Wichitalks/wichitalks.github.io#74]
- Button to "Grab your ticket" is misspelt 
![2017-06-01_2021](https://cloud.githubusercontent.com/assets/540716/26707145/39cf724c-4708-11e7-8f71-2791526b166b.png)
#covfefe

**Comment by kevinfalting** [comment]
Hot damn, looks like I owe you a drink.

**Comment by kevinfalting** [comment]
btw, how big is your monitor!? Good God.
