### ISSUE TITLE
Fine tune the colors

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#8]
Many of the colors that are used are stock, these colors need to be updated to improve the color continuity of the site.

**Comment by kentonh** [comment]
I asked Barry Morgan about this, and I think we're within brand on these colors. He didn't say so explicitly, but the 4 colors to use are the extreme ends of the two different gradients

**Comment by kevinfalting** [comment]
Yeah, he gave me the hex codes for those colors. I can share the dropbox we're using to store all the images.

**Comment by kevinfalting** [comment]
updated colors on commit. closing.
