### ISSUE TITLE
Branding Font

### ISSUE THREAD

**Issue by kevinfalting** [Wichitalks/wichitalks.github.io#9]
There is a specific font that was used for the logo. The script has already been embedded into the <head> and the h1 tag was updated with the font-family.

Also, the first half of Wichitalks is a different color than the second half. See the logo. 

We need to get anything with a h1 tag to use this font.

**Comment by kentonh** [comment]
Do you know what font it is?

**Comment by kevinfalting** [comment]
The script has already been embedded into the `<head>` and the `h1` tag in the `bootstrap.css` file was updated with the `font-family`.

The font is `museo-sans`

This is what Barret gave me:

``` html
<head>
  <script src="https://use.typekit.net/fok3rne.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
```

This next part would go into the CSS file.

``` css
h1 {
  font-family: "museo-sans",sans-serif;
}
```

**Comment by kevinfalting** [comment]
I just imported the logo image instead.
